/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Arrays;

/**
 *
 * @author Pichau
 */
public class CalculadoraJavaSwing extends javax.swing.JFrame {
    private boolean adicao = false;
    private boolean subtração = false;
    private boolean multiplicacao = false;
    private boolean divisao = false;
    Calculos x = new Calculos();
    /**
     * Creates new form NewJFrame
     */
    public CalculadoraJavaSwing() {
        initComponents();
        URL caminhoIcon = getClass().getResource("/calculadora/icon/iconZ.png");
        Image icon = Toolkit.getDefaultToolkit().getImage(caminhoIcon);
        this.setIconImage(icon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        botaooito = new javax.swing.JToggleButton();
        botaosete = new javax.swing.JToggleButton();
        botaonove = new javax.swing.JToggleButton();
        botaodivisao = new javax.swing.JToggleButton();
        botaocinco = new javax.swing.JToggleButton();
        botaoseis = new javax.swing.JToggleButton();
        botaoquatro = new javax.swing.JToggleButton();
        botaomultiplicacao = new javax.swing.JToggleButton();
        botaoum = new javax.swing.JToggleButton();
        botaodois = new javax.swing.JToggleButton();
        botaomenos = new javax.swing.JToggleButton();
        botaotres1 = new javax.swing.JToggleButton();
        botaomais1 = new javax.swing.JToggleButton();
        botaoponto = new javax.swing.JToggleButton();
        botaozero = new javax.swing.JToggleButton();
        botaoapaga = new javax.swing.JToggleButton();
        botaodesliga = new javax.swing.JToggleButton();
        botaoclear = new javax.swing.JToggleButton();
        botaoigual = new javax.swing.JToggleButton();
        visor = new javax.swing.JTextField();
        visordois = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        botaooito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaooito.setText("8");
        botaooito.setFocusPainted(false);
        botaooito.setFocusable(false);
        botaooito.setRequestFocusEnabled(false);
        botaooito.setRolloverEnabled(false);
        botaooito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaooitoActionPerformed(evt);
            }
        });

        botaosete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaosete.setText("7");
        botaosete.setFocusPainted(false);
        botaosete.setFocusable(false);
        botaosete.setRequestFocusEnabled(false);
        botaosete.setRolloverEnabled(false);
        botaosete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoseteActionPerformed(evt);
            }
        });

        botaonove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaonove.setText("9");
        botaonove.setFocusPainted(false);
        botaonove.setFocusable(false);
        botaonove.setRequestFocusEnabled(false);
        botaonove.setRolloverEnabled(false);
        botaonove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaonoveActionPerformed(evt);
            }
        });

        botaodivisao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaodivisao.setText("/");
        botaodivisao.setToolTipText("");
        botaodivisao.setFocusPainted(false);
        botaodivisao.setFocusable(false);
        botaodivisao.setRequestFocusEnabled(false);
        botaodivisao.setRolloverEnabled(false);
        botaodivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaodivisaoActionPerformed(evt);
            }
        });

        botaocinco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaocinco.setText("5");
        botaocinco.setToolTipText("");
        botaocinco.setFocusPainted(false);
        botaocinco.setFocusable(false);
        botaocinco.setRequestFocusEnabled(false);
        botaocinco.setRolloverEnabled(false);
        botaocinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocincoActionPerformed(evt);
            }
        });

        botaoseis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoseis.setText("6");
        botaoseis.setFocusPainted(false);
        botaoseis.setFocusable(false);
        botaoseis.setRequestFocusEnabled(false);
        botaoseis.setRolloverEnabled(false);
        botaoseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoseisActionPerformed(evt);
            }
        });

        botaoquatro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoquatro.setText("4");
        botaoquatro.setFocusPainted(false);
        botaoquatro.setFocusable(false);
        botaoquatro.setRequestFocusEnabled(false);
        botaoquatro.setRolloverEnabled(false);
        botaoquatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoquatroActionPerformed(evt);
            }
        });

        botaomultiplicacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaomultiplicacao.setText("x");
        botaomultiplicacao.setFocusPainted(false);
        botaomultiplicacao.setFocusable(false);
        botaomultiplicacao.setRequestFocusEnabled(false);
        botaomultiplicacao.setRolloverEnabled(false);
        botaomultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaomultiplicacaoActionPerformed(evt);
            }
        });

        botaoum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoum.setText("1");
        botaoum.setFocusPainted(false);
        botaoum.setFocusable(false);
        botaoum.setRequestFocusEnabled(false);
        botaoum.setRolloverEnabled(false);
        botaoum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoumActionPerformed(evt);
            }
        });

        botaodois.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaodois.setText("2");
        botaodois.setFocusPainted(false);
        botaodois.setFocusable(false);
        botaodois.setRequestFocusEnabled(false);
        botaodois.setRolloverEnabled(false);
        botaodois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaodoisActionPerformed(evt);
            }
        });

        botaomenos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaomenos.setText("-");
        botaomenos.setFocusPainted(false);
        botaomenos.setFocusable(false);
        botaomenos.setRequestFocusEnabled(false);
        botaomenos.setRolloverEnabled(false);
        botaomenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaomenosActionPerformed(evt);
            }
        });

        botaotres1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaotres1.setText("3");
        botaotres1.setFocusPainted(false);
        botaotres1.setFocusable(false);
        botaotres1.setRequestFocusEnabled(false);
        botaotres1.setRolloverEnabled(false);
        botaotres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaotres1ActionPerformed(evt);
            }
        });

        botaomais1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaomais1.setText("+");
        botaomais1.setFocusPainted(false);
        botaomais1.setFocusable(false);
        botaomais1.setRequestFocusEnabled(false);
        botaomais1.setRolloverEnabled(false);
        botaomais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaomais1ActionPerformed(evt);
            }
        });

        botaoponto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoponto.setText(".");
        botaoponto.setFocusPainted(false);
        botaoponto.setFocusable(false);
        botaoponto.setRequestFocusEnabled(false);
        botaoponto.setRolloverEnabled(false);
        botaoponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopontoActionPerformed(evt);
            }
        });

        botaozero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaozero.setText("0");
        botaozero.setFocusPainted(false);
        botaozero.setFocusable(false);
        botaozero.setRequestFocusEnabled(false);
        botaozero.setRolloverEnabled(false);
        botaozero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaozeroActionPerformed(evt);
            }
        });

        botaoapaga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoapaga.setText("<");
        botaoapaga.setToolTipText("");
        botaoapaga.setFocusPainted(false);
        botaoapaga.setFocusable(false);
        botaoapaga.setRequestFocusEnabled(false);
        botaoapaga.setRolloverEnabled(false);
        botaoapaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoapagaActionPerformed(evt);
            }
        });

        botaodesliga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaodesliga.setText("OFF");
        botaodesliga.setFocusPainted(false);
        botaodesliga.setFocusable(false);
        botaodesliga.setRequestFocusEnabled(false);
        botaodesliga.setRolloverEnabled(false);
        botaodesliga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaodesligaActionPerformed(evt);
            }
        });

        botaoclear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoclear.setText("CE");
        botaoclear.setFocusPainted(false);
        botaoclear.setFocusable(false);
        botaoclear.setRequestFocusEnabled(false);
        botaoclear.setRolloverEnabled(false);
        botaoclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoclearActionPerformed(evt);
            }
        });

        botaoigual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoigual.setText("=");
        botaoigual.setFocusPainted(false);
        botaoigual.setFocusable(false);
        botaoigual.setRequestFocusEnabled(false);
        botaoigual.setRolloverEnabled(false);
        botaoigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoigualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoapaga, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoclear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(botaodesliga, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaodivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botaoum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botaodois, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(botaoquatro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botaocinco, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(botaosete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botaooito, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoseis, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaonove, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaotres1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaozero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoponto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(botaomais1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaomenos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaomultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoigual, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoclear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoapaga, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaodivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(botaodesliga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaooito, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaosete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaomultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaonove, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaocinco, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoseis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoquatro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaomenos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoum, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaodois, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaotres1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoponto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaomais1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaozero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botaoigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        visor.setEditable(false);
        visor.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorActionPerformed(evt);
            }
        });

        visordois.setBackground(new java.awt.Color(204, 204, 204));
        visordois.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        visordois.setForeground(new java.awt.Color(153, 153, 153));
        visordois.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(visor, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visordois))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(visordois, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaotres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaotres1ActionPerformed
        String valor = visor.getText() + "3";
        visor.setText(valor);
    }//GEN-LAST:event_botaotres1ActionPerformed

    private void botaopontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopontoActionPerformed
        String valor = visor.getText() + ".";
        visor.setText(valor);
    }//GEN-LAST:event_botaopontoActionPerformed

    private void botaozeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaozeroActionPerformed
        String valor = visor.getText() + "0";
        visor.setText(valor);
        
    }//GEN-LAST:event_botaozeroActionPerformed

    private void botaoapagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoapagaActionPerformed
        try{
            String valor = visor.getText();
            String novo_valor = valor.substring(0, valor.length() - 1);
            visor.setText(novo_valor);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_botaoapagaActionPerformed

    private void botaodesligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaodesligaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaodesligaActionPerformed

    private void botaoclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoclearActionPerformed
        visor.setText(null);
        visordois.setText(null);
    }//GEN-LAST:event_botaoclearActionPerformed

    private void botaodivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaodivisaoActionPerformed
        String valor = visor.getText() + "/";
        visor.setText(valor);
        x.setOperador('/');
        visordois.setText(valor);
        visor.setText(null);
    }//GEN-LAST:event_botaodivisaoActionPerformed

    private void botaoseteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoseteActionPerformed
        String valor = visor.getText() + "7";
        visor.setText(valor);
    }//GEN-LAST:event_botaoseteActionPerformed

    private void botaooitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaooitoActionPerformed
        String valor = visor.getText() + "8";
        visor.setText(valor);
    }//GEN-LAST:event_botaooitoActionPerformed

    private void botaonoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaonoveActionPerformed
        String valor = visor.getText() + "9";
        visor.setText(valor);
    }//GEN-LAST:event_botaonoveActionPerformed

    private void botaomultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaomultiplicacaoActionPerformed
        String valor = visor.getText() + "X";
        visor.setText(valor);
        x.setOperador('/');
        visordois.setText(valor);
        visor.setText(null);
    }//GEN-LAST:event_botaomultiplicacaoActionPerformed

    private void botaoquatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoquatroActionPerformed
        String valor = visor.getText() + "4";
        visor.setText(valor);
    }//GEN-LAST:event_botaoquatroActionPerformed

    private void botaocincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocincoActionPerformed
        String valor = visor.getText() + "5";
        visor.setText(valor);
        
    }//GEN-LAST:event_botaocincoActionPerformed

    private void botaoseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoseisActionPerformed
        String valor = visor.getText() + "6";
        visor.setText(valor);
    }//GEN-LAST:event_botaoseisActionPerformed

    private void botaomenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaomenosActionPerformed
        String valor = visor.getText() + "-";
        visor.setText(valor);
        x.setOperador('-');
        visordois.setText(valor);
        visor.setText(null);
    }//GEN-LAST:event_botaomenosActionPerformed

    private void botaoumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoumActionPerformed
        String valor = visor.getText() + "1";
        visor.setText(valor);
    }//GEN-LAST:event_botaoumActionPerformed

    private void botaodoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaodoisActionPerformed
        String valor = visor.getText() + "2";
        visor.setText(valor);
    }//GEN-LAST:event_botaodoisActionPerformed

    private void botaomais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaomais1ActionPerformed
        String valor = visor.getText() + "+";
        visor.setText(valor);
        x.setOperador('+');
        visordois.setText(valor);
        visor.setText(null);
    }//GEN-LAST:event_botaomais1ActionPerformed

    private void botaoigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoigualActionPerformed
        String segundovisor = visordois.getText();
        String nrm1 = visordois.getText().substring(0, visordois.getText().length()-1);
        String nrm2 = visor.getText();
        x.setNumber1(nrm1);
        x.setNumber2(nrm2);
        visor.setText(x.calcular());
        visordois.setText(segundovisor +""+ nrm2);
    }//GEN-LAST:event_botaoigualActionPerformed

    private void visorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJavaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJavaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJavaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJavaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraJavaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoapaga;
    private javax.swing.JToggleButton botaocinco;
    private javax.swing.JToggleButton botaoclear;
    private javax.swing.JToggleButton botaodesliga;
    private javax.swing.JToggleButton botaodivisao;
    private javax.swing.JToggleButton botaodois;
    private javax.swing.JToggleButton botaoigual;
    private javax.swing.JToggleButton botaomais1;
    private javax.swing.JToggleButton botaomenos;
    private javax.swing.JToggleButton botaomultiplicacao;
    private javax.swing.JToggleButton botaonove;
    private javax.swing.JToggleButton botaooito;
    private javax.swing.JToggleButton botaoponto;
    private javax.swing.JToggleButton botaoquatro;
    private javax.swing.JToggleButton botaoseis;
    private javax.swing.JToggleButton botaosete;
    private javax.swing.JToggleButton botaotres1;
    private javax.swing.JToggleButton botaoum;
    private javax.swing.JToggleButton botaozero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField visor;
    private javax.swing.JTextField visordois;
    // End of variables declaration//GEN-END:variables
}
